In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [6]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    3.4s
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:    3.5s finished

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [10]:
re=grid.cv_results_

grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [11]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'splitter': 'best'}: 0.886649700804732

In [12]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[80  5]
 [10 39]]

In [13]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.89      0.94      0.91        85
           1       0.89      0.80      0.84        49

    accuracy                           0.89       134
   macro avg       0.89      0.87      0.88       134
weighted avg       0.89      0.89      0.89       134

In [14]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.868547418967587

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003588,0.001354,0.002594,7.975464e-04,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.826263,0.813511,0.833323,0.906166,0.844370,0.844727,0.032312,5
1,0.002195,0.000399,0.002791,7.457934e-04,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.808927,0.846714,0.703055,0.813179,0.885265,0.811428,0.060747,10
2,0.002593,0.001016,0.002792,3.991411e-04,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.864871,0.868752,0.796284,0.906166,0.906166,0.868448,0.040164,2
3,0.001796,0.000399,0.002397,4.934291e-04,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.867478,0.828959,0.677235,0.888646,0.811321,0.814728,0.073980,9
4,0.001994,0.000001,0.001995,6.302998e-04,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.867478,0.815037,0.851527,0.925272,0.923510,0.876565,0.042594,1
5,0.001796,0.000399,0.001795,3.989220e-04,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.804764,0.870047,0.851527,0.885265,0.862442,0.854809,0.027325,3
6,0.001795,0.000399,0.001596,4.884422e-04,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.826263,0.850809,0.775815,0.832483,0.847020,0.826478,0.026896,7
7,0.002194,0.000399,0.001596,4.891227e-04,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.832255,0.831253,0.814409,0.831098,0.847020,0.831207,0.010328,6
8,0.001196,0.000399,0.001795,3.988747e-04,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.826263,0.828959,0.777291,0.833323,0.865054,0.826178,0.028143,8
9,0.001795,0.000399,0.001396,4.886565e-04,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.867478,0.811321,0.720804,0.795256,0.829124,0.804797,0.048392,11
10,0.001396,0.000489,0.001995,7.231594e-07,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.847141,0.868752,0.796284,0.851527,0.905069,0.853755,0.035241,4
11,0.001795,0.000747,0.001595,4.889090e-04,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.737140,0.868752,0.759721,0.829124,0.826499,0.804247,0.048499,12

In [17]:
age_input=float(input("Age:"))
estimatedsalary_input=float(input("Estimated Salary:"))
#children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
#smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:35
Estimated Salary:20000
Sex Male 0 or 1:1

In [18]:
Future_Prediction=grid.predict([[age_input,estimatedsalary_input,sex_male_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]