In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
dataset = pd.get_dummies (dataset,drop_first=True)

In [6]:
indep = dataset[['R&D Spend','Administration','Marketing Spend','State_Florida','State_New York']]
dep = dataset[['Profit']]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(indep,dep,test_size = 0.03, random_state = 0)

In [8]:
#Standardisation

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Grid

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    3.4s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    3.7s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    3.7s finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [11]:
# print best parameter after tuning
#print(grid.best_params_)

In [12]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004986,0.000631,0.004788,7.451679e-04,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.050949,-0.013321,-0.139694,0.000048,-0.003226,-0.041428,0.052377,39
1,0.004788,0.000978,0.004587,1.352058e-03,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",-0.047279,-0.007516,-0.137583,0.002574,-0.001283,-0.038217,0.052775,36
2,0.003789,0.000747,0.004589,4.895814e-04,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.048048,-0.009237,-0.136949,0.002610,-0.000962,-0.038517,0.052419,38
3,0.003790,0.001164,0.003789,7.462510e-04,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.028300,0.016791,-0.116959,0.020894,0.015224,-0.018470,0.052392,31
4,0.004788,0.001321,0.004388,1.015372e-03,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.050962,-0.013353,-0.139632,0.000052,-0.003252,-0.041429,0.052347,40
5,0.004588,0.000799,0.003789,9.766788e-04,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.047036,-0.006771,-0.138342,0.002496,-0.000831,-0.038097,0.053192,35
6,0.005585,0.001739,0.004188,7.471431e-04,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.048007,-0.009120,-0.137188,0.002592,-0.000853,-0.038515,0.052533,37
7,0.003990,0.001410,0.003989,6.303750e-04,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.028300,0.016791,-0.116959,0.020894,0.015224,-0.018470,0.052392,31
8,0.003992,0.001096,0.004388,7.979413e-04,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.042516,-0.002586,-0.128097,0.009551,0.005425,-0.031645,0.051647,34
9,0.004388,0.000798,0.003392,1.017355e-03,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",-0.007894,0.053138,-0.107324,0.034453,0.024606,-0.000604,0.056912,28
10,0.004987,0.001411,0.004389,4.882111e-04,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.016749,0.031893,-0.101215,0.034862,0.027789,-0.004684,0.051807,29
11,0.004186,0.001714,0.003391,4.886000e-04,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.145957,0.260206,0.075501,0.201248,0.171909,0.170964,0.061026,21
12,0.005186,0.001465,0.003195,3.974699e-04,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.042645,-0.002858,-0.127477,0.009599,0.005159,-0.031644,0.051360,33
13,0.003985,0.000006,0.003393,4.903534e-04,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-0.005813,0.059474,-0.114743,0.033687,0.029041,0.000329,0.061179,27
14,0.004189,0.000399,0.002794,3.997399e-04,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.016415,0.032781,-0.103525,0.034679,0.028860,-0.004724,0.052887,30
15,0.005386,0.001353,0.002992,6.843901e-07,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.145957,0.260206,0.075501,0.201248,0.171909,0.170964,0.061026,21
16,0.004189,0.000977,0.003391,4.884610e-04,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.026041,0.093977,-0.023185,0.097006,0.081531,0.055074,0.046774,26
17,0.004191,0.000977,0.003190,3.995317e-04,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.327713,0.531127,0.159636,0.312184,0.253141,0.316760,0.122335,16
18,0.004587,0.001352,0.002593,4.879746e-04,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.245117,0.386940,0.234090,0.312202,0.269315,0.289533,0.055601,17
19,0.003790,0.000977,0.002593,4.887145e-04,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.819378,0.931796,0.883062,0.791486,0.807924,0.846729,0.052654,5
20,0.004788,0.001828,0.003192,3.988031e-04,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.025059,0.091468,-0.017536,0.097436,0.079099,0.055105,0.044428,25
21,0.004388,0.001738,0.002993,8.915904e-04,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.342797,0.571804,0.094058,0.306333,0.286466,0.320291,0.152503,15
22,0.003989,0.000631,0.002793,7.465952e-04,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.247784,0.394370,0.209819,0.311074,0.278224,0.288254,0.062725,18
23,0.005386,0.001739,0.002793,3.991624e-04,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.819378,0.931796,0.883062,0.791486,0.807924,0.846729,0.052654,5
24,0.003391,0.000798,0.003192,9.763576e-04,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.095551,0.189499,0.087863,0.182548,0.155236,0.142139,0.042811,24
25,0.005584,0.002930,0.003391,4.887335e-04,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.553151,0.825597,0.428968,0.473963,0.443170,0.544970,0.146752,11
26,0.005186,0.002393,0.002793,3.992323e-04,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.509226,0.676746,0.477715,0.512413,0.500307,0.535281,0.071765,14
27,0.005584,0.001740,0.003392,7.999184e-04,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.881953,0.924718,0.954689,0.870307,0.903771,0.907088,0.030240,3
28,0.005385,0.002931,0.003193,4.002337e-04,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.093611,0.184729,0.100758,0.183372,0.150772,0.142648,0.039127,23
29,0.003991,0.000002,0.002991,6.327869e-04,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.571212,0.853536,0.315443,0.468995,0.495065,0.540850,0.177066,12
30,0.004188,0.001595,0.002594,4.883830e-04,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.514758,0.683529,0.462277,0.510332,0.514645,0.537108,0.075842,13
31,0.004987,0.001545,0.003790,7.461750e-04,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.881953,0.924718,0.954689,0.870307,0.903771,0.907088,0.030240,3
32,0.004787,0.002475,0.003590,4.884817e-04,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.159848,0.274945,0.190217,0.256724,0.235837,0.223514,0.042572,20
33,0.004588,0.000798,0.003592,7.978917e-04,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.694910,0.897642,0.540025,0.549551,0.574575,0.651341,0.135062,10
34,0.005585,0.002410,0.003391,7.976775e-04,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.670054,0.798626,0.712520,0.674357,0.670263,0.705164,0.049374,7
35,0.004187,0.000394,0.003391,4.887735e-04,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.906932,0.918480,0.956512,0.880454,0.946942,0.921864,0.027490,1
36,0.004589,0.001353,0.003390,4.889870e-04,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.157130,0.268050,0.209660,0.257788,0.229579,0.224441,0.039470,19
37,0.004587,0.001739,0.003192,3.985910e-04,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.712928,0.899415,0.478891,0.549602,0.622761,0.652719,0.145761,9
38,0.004786,0.001163,0.002793,3.988749e-04,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.670362,0.797703,0.673564,0.674021,0.672356,0.697601,0.050067,8
39,0.003590,0.001017,0.002194,3.986607e-04,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.906932,0.918480,0.956512,0.880454,0.946942,0.921864,0.027490,1

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:23
BMI:56
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,→change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[874386.73147377]

In [17]:
import pickle
filename="finalized_model_svr.sav"

In [19]:
pickle.dump(grid,open(filename,'wb'))

In [20]:
preinput=sc.transform([[1300,12000,4000,0,1]])

In [21]:
preinput

array([[-1.55888979, -4.09490444, -1.69649936, -0.67419986,  1.35038121]])

In [23]:
loaded_model=pickle.load(open("finalized_model_svr.sav",'rb'))
result=loaded_model.predict(preinput)

In [24]:
result

array([49117.46366344])