In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
print(dataset.iloc[1])

age                       3.000000
bp                       76.459948
al                        2.000000
su                        0.000000
bgr                     148.112676
bu                       22.000000
sc                        0.700000
sod                     137.528754
pot                       4.627244
hrmo                     10.700000
pcv                      34.000000
wc                    12300.000000
rc                        4.705597
sg_b                      0.000000
sg_c                      1.000000
sg_d                      0.000000
sg_e                      0.000000
rbc_normal                1.000000
pc_normal                 1.000000
pcc_present               0.000000
ba_present                0.000000
htn_yes                   0.000000
dm_yes                    0.000000
cad_yes                   0.000000
appet_yes                 1.000000
pe_yes                    0.000000
ane_yes                   0.000000
classification_yes        1.000000
Name: 1, dtype: float64

In [7]:
print(dataset.columns)

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 

grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    3.5s
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:    3.6s finished

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_

grid_predictions = grid.predict(X_test) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'random'}: 0.955283779067923

In [15]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 6 76]]

In [16]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133

In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9634146341463414

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002140,0.000292,0.002794,0.000749,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.926978,0.924528,0.907035,0.962264,0.962573,0.936676,0.022116,12
1,0.001996,0.000003,0.002394,0.000489,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.890467,0.943041,0.962573,0.962264,0.981217,0.947913,0.031157,7
2,0.001594,0.000491,0.002194,0.000397,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.961755,0.906705,0.906085,0.961826,0.939931,0.027388,10
3,0.001596,0.000799,0.002393,0.000798,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.944161,0.962573,0.962264,0.962573,0.962628,0.011832,4
4,0.001596,0.000488,0.001995,0.000630,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.922185,0.962573,0.981031,1.000000,0.965815,0.025771,2
5,0.001995,0.001093,0.002194,0.000399,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.925272,0.981217,0.962264,1.000000,0.962771,0.026249,3
6,0.001995,0.000631,0.002194,0.000400,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.945100,0.924528,0.944023,0.943651,0.962264,0.943913,0.011950,8
7,0.001596,0.000488,0.001596,0.000489,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.962963,0.981014,1.000000,0.981031,0.887719,0.962545,0.039204,5
8,0.001197,0.000399,0.001595,0.000489,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.963284,0.906166,0.925524,0.962264,0.962264,0.943900,0.023714,9
9,0.000997,0.000001,0.001596,0.000489,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.890759,0.981014,0.944023,0.981217,1.000000,0.959403,0.038832,6
10,0.001396,0.000489,0.001795,0.000399,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.869709,0.925146,0.962264,0.942332,0.939890,0.043041,11
11,0.001197,0.000399,0.001596,0.000489,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.962264,0.981217,1.000000,0.962573,0.977525,0.014082,1

In [20]:
age_input=float(input("Age:"))
bp_input=float(input("bp:"))
al_input=float(input("al:"))
su_input=float(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pcv:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=float(input("sg_b yes 0 or 1:"))
sg_c_input=float(input("sg_c Yes 0 or 1:"))
sg_d_input=float(input("sg_d Yes 0 or 1:"))
sg_e_input=float(input("sg_e Yes 0 or 1:"))
rbc_normal_input=float(input("rbc Normal 0 or 1:"))
pc_normal_input=float(input("pc Normal 0 or 1:"))
pcc_present_input=float(input("pcc Present 0 or 1:"))
ba_present_input=float(input("ba Present 0 or 1:"))
htn_yes_input=float(input("htn Yes 0 or 1:"))
dm_yes_input=float(input("dm Yes 0 or 1:"))
cad_yes_input=float(input("cad Yes 0 or 1:"))
appet_yes_input=float(input("appet Yes 0 or 1:"))
pe_yes_input=float(input("pe Good 0 or 1:"))
ane_yes_input=float(input("ane Yes 0 or 1:"))

Age:22
bp:60
al:0
su:0
bgr:97
bu:18
sc:1.2
sod:138
pot:4.3
hrmo:13.5
pcv:42
wc:7900
rc:6.4
sg_b yes 0 or 1:1
sg_c Yes 0 or 1:0
sg_d Yes 0 or 1:0
sg_e Yes 0 or 1:0
rbc Normal 0 or 1:1
pc Normal 0 or 1:1
pcc Present 0 or 1:0
ba Present 0 or 1:0
htn Yes 0 or 1:0
dm Yes 0 or 1:0
cad Yes 0 or 1:0
appet Yes 0 or 1:1
pe Good 0 or 1:0
ane Yes 0 or 1:0

In [ ]:
#'age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
     #  'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
      # 'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
      # 'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      #dtype='object'

In [22]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[0]