In [1]:
import  numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies (dataset,drop_first=True)

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [ ]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, Y_train, Y_test = train_test_split(indep,dep,test_size = 0.03, random_state = 0)

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [6]:
from sklearn.ensemble import RandomForestRegressor

In [7]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion': ['squared_error', 'absolute_error'],
    'max_features': ['sqrt', 'log2', None],
    'n_estimators': [10, 100]}

In [9]:
grid = GridSearchCV(
    RandomForestRegressor(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
#grid_predictions = grid.predict(X_test)
# print classification report
#from sklearn.metrics import r2_score
#r_score=r2_score(Y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.054654,0.001466,0.007580,3.191352e-03,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.841928,0.747738,0.853377,0.811283,0.816236,0.814112,0.036697,10
1,0.447602,0.007501,0.018750,3.992325e-04,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.858734,0.780178,0.857781,0.825737,0.841784,0.832843,0.028970,4
2,0.050265,0.004574,0.005186,7.462894e-04,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.846817,0.749734,0.849302,0.812315,0.826557,0.816945,0.036251,7
3,0.442616,0.008496,0.018751,7.482669e-04,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.859612,0.782160,0.862149,0.830508,0.839209,0.834727,0.028887,1
4,0.065624,0.002779,0.005186,3.988508e-04,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.840155,0.760129,0.838650,0.809687,0.832227,0.816170,0.030070,8
5,0.589025,0.004214,0.018749,1.323025e-03,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.847817,0.769706,0.857668,0.818691,0.834319,0.825640,0.030886,5
6,0.150396,0.006951,0.004987,5.352484e-07,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.827402,0.761879,0.821393,0.812172,0.830259,0.810621,0.025145,12
7,1.448126,0.015820,0.017353,4.890449e-04,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.857156,0.778494,0.859869,0.828699,0.845757,0.833995,0.029842,2
8,0.148203,0.003373,0.004787,3.989936e-04,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.846862,0.763594,0.840452,0.816031,0.811451,0.815678,0.029384,9
9,1.434563,0.026225,0.017553,1.196218e-03,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.860962,0.779430,0.854878,0.830804,0.839485,0.833112,0.028903,3
10,0.257909,0.001849,0.004388,4.883054e-04,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.817242,0.768118,0.826755,0.820382,0.822903,0.811080,0.021706,11
11,2.066473,0.053656,0.013971,2.083332e-03,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.834564,0.771718,0.852422,0.822919,0.835687,0.823462,0.027529,6

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:5
BMI:56
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5648.0163778]

C:\Users\User\.conda\envs\myenv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(